all:
  hosts:
    master1:
      ansible_host: 10.1.2.10
      ip: 10.1.2.10
      access_ip: 10.1.2.10
    node2:
      ansible_host: 10.1.2.6
      ip: 10.1.2.6
      access_ip: 10.1.2.6
    node3:
      ansible_host: 10.1.2.32
      ip: 10.1.2.32
      access_ip: 10.1.2.32
    node4:
      ansible_host: 10.1.2.3
      ip: 10.1.2.3
      access_ip: 10.1.2.3
  children:
    kube_control_plane:
      hosts:
        master1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        master1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}