apiVersion: v1
kind: Pod
metadata:
  labels:
    app: echoserver1
  name: hello-world
spec:
  containers:
    - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      name: hello-world
      ports:
        - containerPort: 8080


