apiVersion: v1
kind: Pod
metadata:
  labels:
    app: echoserver
  name: netology-web
spec:
  containers:
    - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      name: netology-web
      ports:
        - containerPort: 8080


