apiVersion: v1
kind: Service
metadata:
  name:  nginx-multitool-svc
  namespace: default
spec:
  ports:
    - name: web
      port: 9001
      targetPort: 80
    - name: multitool
      port: 9002
      targetPort: 8080 
  selector:
    app: nginx-multitool
  type: ClusterIP 