apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool
  namespace: default
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # maxSurge: 25%
      # maxUnavailable: 25%
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - image: nginx:1.28
        imagePullPolicy: IfNotPresent
        name: nginx
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        lifecycle:
          postStart:
            exec:
              command: ["sleep", "10"]
          preStop:
            exec:
              command: ["sleep", "30"]
